function SortByName(x,y) {return ((x.title.$t == y.title.$t) ? 0 : ((x.title.$t > y.title.$t) ? 1 : -1 ))}
function domcolor(dom) {$('#pages_Label .post-date').css('background',dom);$('#pages_Label .post-outer').css('border-color',dom); $('#pages_Label .post-outer a').css('color',dom); $('#pages_Label .post-title').css('color',dom);$('#pages_Label .Night.post-title').css('color','#ffffff')}
function parseLabel(a) { var e=a.feed.entry; for (var i = 0; i < e.length; i++) { for (var l=0;l<e[i].link.length;l++){if (e[i].link[l].rel=="alternate"){var link= e[i].link[l].href;break}}; var title=e[i].title.$t,date=e[i].published.$t;try {img=e[i].media$thumbnail.url} catch (h) {s = e[i].content.$t;a = s.indexOf('<img');b =s.indexOf('src="', a);c = s.indexOf('"', b + 5);d = s.substr(b + 5, c - b - 5);if (a != -1 && b != -1 && c != -1 && d != '') {img=d}}; for(var j=0;j<e[i].category.length;j++){if(e[i].category[j].term=='Mobile Legends: Bang Bang'){var cat='https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEhsFeYJetvdMrSXfy2kZRlbtUl9OXWTH5jKoTjTOAdVp6U7MhIk2pAVo5JQCL4VogIUFyt8z_uPHLVWdEfUyw0ghgz29wrgnla39YnRZAMSHx4rxw05PK2Dgbm5-Bu5S6SJ_t541Xj3qEVZ6upSGxqSiJCLt08L-R0sc0VZCFBtsTQvxo1WI73ZJbLFzQ/w100-rw/MLBB.png'}
if(e[i].category[j].term=='League of Legends: Wild Rift'){var cat='https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEjkY_rmNBv9SPNflhBzM6FZLK4BIDXBk5nUytlfvLCaCLspM9d6JVVrsFdHLY8Jw3wRrWNmYMIQgNgCkjSHEFINK64tvx-piJUp73FoioNVTG84GZayw-ybT2RDGnsKSXcVzQAFv9nMhxpoyP2jRbrLlRl-uz7L97rfcub47xmimM2xO34dZDzLSX_ApA/w100-rw/LOLWR.png'}
if(e[i].category[j].term=='League of Legends'){var cat='https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEhELQD0dWEUqEoyDDlmoaUtDulEkEA_Md0Ag583lCStNJnlEY2Sw7GJyNHXL_DBGcpdxc31PkdJYEwRRfTEraCxjpSeTt-bEXK8H841v7fRZbnpGqwbLZAuhWNAbC7sYNAUA5nMnCvoJO08jS7vQu3b8MfuVRMZV2gsbS2tI72ejESkuF3jGgFwPAZWiQ/w100-rw/League_of_Legends.png'}
if(e[i].category[j].term=='Arena of Valor'){var cat='https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEgCDOsHeQvFe_vr9RFsy1zkYVxdPcrlmJ6vd6VGQT4aK5Z9d5tZGkvIaTHZEXjxwihLrxVHbXMcsebvGR79mITEoAWHX-EtbxnWCMRykW94Mt1vbi0hnumSiv_wBdiD5bEF6AJ-se9lsCVYHfvKYBKQQ6XhOpC7M31p4FFMs1q9rFerPI5POVrVXkajEQ/w100-rw/AOV.png'}
if(e[i].category[j].term=='Onmyoji Arena'){var cat='https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEh0cv-szl8E8HiaekfRq1vs7hV67mcKuaUX8huK2lBOkbb4LVCqhBVTBjFoL4rbEeJSqpAfidHuO2CeTTpF3Fr_XQr1cCNkBVcfXzGO5D-6jIVp6xVPeGTdBelGW67WDTGcJshnZLUBHTLyuoe3eCDKslIfuc62iNwp6QlDKjGGJ8pB4cminJPB1YrFxw/w100-rw/ONMYOJI.png'}} 
if(i%12 == 0 && i != 0){$('#feature_pages_Label').append('<div class="post-outer-for-ads"><ins class="adsbygoogle" data-ad-client="ca-pub-2746726314208711" data-ad-format="rectangle, horizontal" data-ad-slot="3245642180" data-full-width-responsive="false"/></div>');
(adsbygoogle = window.adsbygoogle || []).push({})}; $('#feature_pages_Label').append('<div class="post-outer"><a href="' + link + '" title="' + title + '"><div class="first-thumb" style="background-image:url(' + img + ')"><div class="post-date">' + date.substring(0, 4) + '</div><div class="caty" style="display:block;position:absolute;bottom:5px;left:5px;background-image: url(' + cat + ');background-repeat: no-repeat; background-position: center;background-size:contain;width:20px;height:20px;background-color:rgba(0,0,0,.7);border-radius:2px"></div></div><h5 class="notranslate post-title">' + title + '</h5></a></div>')}; $('#pages_Label .loadinggames').addClass('hidden'); $('#pages_Label .btn-load-list').removeClass('hidden')}
function parseCurrLabel(a) { var e=a.feed.entry; for (var i = 0; i < e.length; i++) { for (var l=0;l<e[i].link.length;l++){if (e[i].link[l].rel=="alternate"){var link= e[i].link[l].href;break}}; var title=e[i].title.$t,date=e[i].published.$t;try {img=e[i].media$thumbnail.url} catch (h) {s = e[i].content.$t;a = s.indexOf('<img');b =s.indexOf('src="', a);c = s.indexOf('"', b + 5);d = s.substr(b + 5, c - b - 5);if (a != -1 && b != -1 && c != -1 && d != '') {img=d}}; 
if(i%12 == 0 && i != 0){$('#feature_pages_Label').append('<div class="post-outer-for-ads"><ins class="adsbygoogle" data-ad-client="ca-pub-2746726314208711" data-ad-format="rectangle, horizontal" data-ad-slot="3245642180" data-full-width-responsive="false"/></div>');
(adsbygoogle = window.adsbygoogle || []).push({})}; $('#feature_pages_Label').append('<div class="post-outer"><a href="' + link + '" title="' + title + '"><div class="first-thumb" style="background-image:url(' + img + ')"><div class="post-date">' + date.substring(0, 4) + '</div></div><h5 class="notranslate post-title">' + title + '</h5></a></div>')}; $('#pages_Label .loadinggames').addClass('hidden'); $('#pages_Label .btn-load-list').removeClass('hidden')}
function parseTypeLabel(a) { var e=a.feed.entry.sort(SortByName); for (var i = 0; i < e.length; i++) { for (var l=0;l<e[i].link.length;l++){if (e[i].link[l].rel=="alternate"){var link= e[i].link[l].href;break}}; var title=e[i].title.$t,date=e[i].published.$t;try {img=e[i].media$thumbnail.url} catch (h) {s = e[i].content.$t;a = s.indexOf('<img');b =s.indexOf('src="', a);c = s.indexOf('"', b + 5);d = s.substr(b + 5, c - b - 5);if (a != -1 && b != -1 && c != -1 && d != '') {img=d}}; for(var j=0;j<e[i].category.length;j++){if(e[i].category[j].term=='Mobile Legends: Bang Bang'){var cat='https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEhsFeYJetvdMrSXfy2kZRlbtUl9OXWTH5jKoTjTOAdVp6U7MhIk2pAVo5JQCL4VogIUFyt8z_uPHLVWdEfUyw0ghgz29wrgnla39YnRZAMSHx4rxw05PK2Dgbm5-Bu5S6SJ_t541Xj3qEVZ6upSGxqSiJCLt08L-R0sc0VZCFBtsTQvxo1WI73ZJbLFzQ/w100-rw/MLBB.png'}
if(e[i].category[j].term=='League of Legends: Wild Rift'){var cat='https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEjkY_rmNBv9SPNflhBzM6FZLK4BIDXBk5nUytlfvLCaCLspM9d6JVVrsFdHLY8Jw3wRrWNmYMIQgNgCkjSHEFINK64tvx-piJUp73FoioNVTG84GZayw-ybT2RDGnsKSXcVzQAFv9nMhxpoyP2jRbrLlRl-uz7L97rfcub47xmimM2xO34dZDzLSX_ApA/w100-rw/LOLWR.png'}
if(e[i].category[j].term=='League of Legends'){var cat='https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEhELQD0dWEUqEoyDDlmoaUtDulEkEA_Md0Ag583lCStNJnlEY2Sw7GJyNHXL_DBGcpdxc31PkdJYEwRRfTEraCxjpSeTt-bEXK8H841v7fRZbnpGqwbLZAuhWNAbC7sYNAUA5nMnCvoJO08jS7vQu3b8MfuVRMZV2gsbS2tI72ejESkuF3jGgFwPAZWiQ/w100-rw/League_of_Legends.png'}
if(e[i].category[j].term=='Arena of Valor'){var cat='https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEgCDOsHeQvFe_vr9RFsy1zkYVxdPcrlmJ6vd6VGQT4aK5Z9d5tZGkvIaTHZEXjxwihLrxVHbXMcsebvGR79mITEoAWHX-EtbxnWCMRykW94Mt1vbi0hnumSiv_wBdiD5bEF6AJ-se9lsCVYHfvKYBKQQ6XhOpC7M31p4FFMs1q9rFerPI5POVrVXkajEQ/w100-rw/AOV.png'}
if(e[i].category[j].term=='Onmyoji Arena'){var cat='https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEh0cv-szl8E8HiaekfRq1vs7hV67mcKuaUX8huK2lBOkbb4LVCqhBVTBjFoL4rbEeJSqpAfidHuO2CeTTpF3Fr_XQr1cCNkBVcfXzGO5D-6jIVp6xVPeGTdBelGW67WDTGcJshnZLUBHTLyuoe3eCDKslIfuc62iNwp6QlDKjGGJ8pB4cminJPB1YrFxw/w100-rw/ONMYOJI.png'}}
if(i%12 == 0 && i != 0){$('#feature_pages_Label').append('<div class="post-outer-for-ads"><ins class="adsbygoogle" data-ad-client="ca-pub-2746726314208711" data-ad-format="rectangle, horizontal" data-ad-slot="3245642180" data-full-width-responsive="false"/></div>');
(adsbygoogle = window.adsbygoogle || []).push({})}; $('#feature_pages_Label').append('<div class="post-outer"><a href="' + link + '" title="' + title + '"><div class="first-thumb" style="background-image:url(' + img + ')"><div class="post-date">' + date.substring(0, 4) + '</div><div class="caty" style="display:block;position:absolute;bottom:5px;left:5px;background-image: url(' + cat + ');background-repeat: no-repeat; background-position: center;background-size:contain;width:20px;height:20px;background-color:rgba(0,0,0,.7);border-radius:2px"></div></div><h5 class="notranslate post-title">' + title + '</h5></a></div>')}; $('#pages_Label .loadinggames').addClass('hidden'); $('#pages_Label .btn-load-list').removeClass('hidden')}
function CallAjax(lb,cb,dc){var numposts=24; $.ajax({type: 'GET',url: '/feeds/posts/default/-/' + lb,data: {'max-results': numposts,'alt': 'json'},dataType: 'jsonp',jsonp: 'callback',jsonpCallback: cb,success: function(e) {var totalposts = e.feed.openSearch$totalResults.$t; $('#pages_Label .allposts').attr('value', totalposts); domcolor(dc); $('#pages_Label .btn-load-list').click(function() {$('#pages_Label .readyloadcontent').removeClass('hidden'); $('#pages_Label .btn-load-list').addClass('hidden'); var items = Number($('#pages_Label .numposts').val()); var curritems = items + numposts; if (curritems <= totalposts) { $('#pages_Label .numposts').val(curritems); $.ajax({type: 'GET',url: '/feeds/posts/default/-/' + lb,data: {'max-results': numposts,'start-index': curritems + 1,'alt': 'json'},dataType: 'jsonp',jsonp: 'callback',jsonpCallback: cb,success: function() { domcolor(dc); var lastposts = curritems + numposts; if (lastposts > totalposts) { $('#pages_Label .btn-load-list,#pages_Label .readyloadcontent').addClass('hidden')} else {$('#pages_Label .readyloadcontent').addClass('hidden')}}})} else {$('#pages_Label .btn-load-list,#pages_Label .readyloadcontent').addClass('hidden')}})}})}
function CallAjaxRole(lbl,role,clr){$.ajax({type: 'GET',url: '/feeds/posts/default/-/' + lbl,data: {'max-results': '999999','alt': 'json'},dataType: 'jsonp',success: function(a) { var e=a.feed.entry.sort(SortByName); $('#feature_pages_Label').html('<div class="child_feature_pages_Label" style="width:100%;margin:0;padding:0"></div>'); for (var i = 0; i < e.length; i++) { for (var l=0;l<e[i].link.length;l++){if (e[i].link[l].rel=="alternate"){var link= e[i].link[l].href;break}}; var title=e[i].title.$t,date=e[i].published.$t;try {img=e[i].media$thumbnail.url} catch (h) {s = e[i].content.$t;a = s.indexOf('<img');b =s.indexOf('src="', a);c = s.indexOf('"', b + 5);d = s.substr(b + 5, c - b - 5);if (a != -1 && b != -1 && c != -1 && d != '') {img=d}};
for(var j=0;j<e[i].category.length;j++){ if(e[i].category[j].term==role){$('.child_feature_pages_Label').append('<div class="post-outer"><a href="' + link + '" title="' + title + '"><div class="first-thumb" style="background-image:url(' + img + ')"><div class="post-date">' + date.substring(0, 4) + '</div></div><h5 class="notranslate post-title">' + title + '</h5></a></div>')}}}; $('.child_feature_pages_Label').append('<div class="post-outer-for-ads"><ins class="adsbygoogle" data-ad-client="ca-pub-2746726314208711" data-ad-format="rectangle, horizontal" data-ad-slot="3245642180" data-full-width-responsive="false"/></div>');
(adsbygoogle = window.adsbygoogle || []).push({}); $('.child_feature_pages_Label .post-date').css('background',clr); $('.child_feature_pages_Label .post-outer').css('border-color',clr); $('.child_feature_pages_Label .post-outer a').css('color',clr); $('#pages_Label .loadinggames').addClass('hidden')}})}
function CallAjaxYear(lbl,year,clr){$.ajax({type: 'GET',url: '/feeds/posts/default/-/' + lbl,data: {'max-results': '999999','alt': 'json'},dataType: 'jsonp',success: function(a) { var e=a.feed.entry.sort(SortByName); $('#feature_pages_Label').html('<div class="child_feature_pages_Label" style="width:100%;margin:0;padding:0"></div>'); for (var i = 0; i < e.length; i++) { for (var l=0;l<e[i].link.length;l++){if (e[i].link[l].rel=="alternate"){var link= e[i].link[l].href;break}}; var title=e[i].title.$t,date=e[i].published.$t.substring(0, 4); try {img=e[i].media$thumbnail.url} catch (h) {s = e[i].content.$t;a = s.indexOf('<img');b =s.indexOf('src="', a);c = s.indexOf('"', b + 5);d = s.substr(b + 5, c - b - 5);if (a != -1 && b != -1 && c != -1 && d != '') {img=d}};
for(var j=0;j<e[i].yearofdate.length;j++){ if(date==year){$('.child_feature_pages_Label').append('<div class="post-outer"><a href="' + link + '" title="' + title + '"><div class="first-thumb" style="background-image:url(' + img + ')"><div class="post-date">' + date + '</div></div><h5 class="notranslate post-title">' + title + '</h5></a></div>')}}}; $('.child_feature_pages_Label').append('<div class="post-outer-for-ads"><ins class="adsbygoogle" data-ad-client="ca-pub-2746726314208711" data-ad-format="rectangle, horizontal" data-ad-slot="3245642180" data-full-width-responsive="false"/></div>');
(adsbygoogle = window.adsbygoogle || []).push({}); $('.child_feature_pages_Label .post-date').css('background',clr); $('.child_feature_pages_Label .post-outer').css('border-color',clr); $('.child_feature_pages_Label .post-outer a').css('color',clr); $('#pages_Label .loadinggames').addClass('hidden')}})}
