$("#modedark").click(function(){$("body").toggleClass("Night")}),$("body").toggleClass(localStorage.toggled),$("#modedark").click(function(){
"Night"!=localStorage.toggled?($("body").toggleClass("Night",!0),localStorage.toggled="Night"):($("body").toggleClass("Night",!1),localStorage.toggled="")}); if (localStorage.toggled == "Night") {$(".post-body font").removeAttr("color"); $(".post-body font").replaceWith(function () { return "<b>" + $(this).text() + "</b>"; });}else{};
function newsPosts(a){var e=a.feed.entry,title,link,cat,date,content="",ct=document.getElementById("news-posts");for(var i=0;i<e.length;i++){for(var j=0;j<e[i].category.length;j++){
if(e[i].category[j].term=='Mobile Legends: Bang Bang'){var cat='https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEhsFeYJetvdMrSXfy2kZRlbtUl9OXWTH5jKoTjTOAdVp6U7MhIk2pAVo5JQCL4VogIUFyt8z_uPHLVWdEfUyw0ghgz29wrgnla39YnRZAMSHx4rxw05PK2Dgbm5-Bu5S6SJ_t541Xj3qEVZ6upSGxqSiJCLt08L-R0sc0VZCFBtsTQvxo1WI73ZJbLFzQ/w100-rw/MLBB.png'}
if(e[i].category[j].term=='League of Legends: Wild Rift'){var cat='https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEjkY_rmNBv9SPNflhBzM6FZLK4BIDXBk5nUytlfvLCaCLspM9d6JVVrsFdHLY8Jw3wRrWNmYMIQgNgCkjSHEFINK64tvx-piJUp73FoioNVTG84GZayw-ybT2RDGnsKSXcVzQAFv9nMhxpoyP2jRbrLlRl-uz7L97rfcub47xmimM2xO34dZDzLSX_ApA/w100-rw/LOLWR.png'}
if(e[i].category[j].term=='League of Legends'){var cat='https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEhELQD0dWEUqEoyDDlmoaUtDulEkEA_Md0Ag583lCStNJnlEY2Sw7GJyNHXL_DBGcpdxc31PkdJYEwRRfTEraCxjpSeTt-bEXK8H841v7fRZbnpGqwbLZAuhWNAbC7sYNAUA5nMnCvoJO08jS7vQu3b8MfuVRMZV2gsbS2tI72ejESkuF3jGgFwPAZWiQ/w100-rw/League_of_Legends.png'}
if(e[i].category[j].term=='Arena of Valor'){var cat='https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEgCDOsHeQvFe_vr9RFsy1zkYVxdPcrlmJ6vd6VGQT4aK5Z9d5tZGkvIaTHZEXjxwihLrxVHbXMcsebvGR79mITEoAWHX-EtbxnWCMRykW94Mt1vbi0hnumSiv_wBdiD5bEF6AJ-se9lsCVYHfvKYBKQQ6XhOpC7M31p4FFMs1q9rFerPI5POVrVXkajEQ/w100-rw/AOV.png'}
if(e[i].category[j].term=='Onmyoji Arena'){var cat='https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEh0cv-szl8E8HiaekfRq1vs7hV67mcKuaUX8huK2lBOkbb4LVCqhBVTBjFoL4rbEeJSqpAfidHuO2CeTTpF3Fr_XQr1cCNkBVcfXzGO5D-6jIVp6xVPeGTdBelGW67WDTGcJshnZLUBHTLyuoe3eCDKslIfuc62iNwp6QlDKjGGJ8pB4cminJPB1YrFxw/w100-rw/ONMYOJI.png'}} var title=e[i].title.$t; for (var l=0;l<e[i].link.length;l++){if (e[i].link[l].rel=="alternate"){var link= e[i].link[l].href;break}}; var date=e[i].published.$t;content+='<a href="'+link+'" title="'+title+'" rel="nofollow" style="color:#ffb3b3"><span class="notranslate" style="margin-right:15px;border:0.5px solid #fcfcfc;border-radius:5px;padding:3px"><span class="caty" style="display:inline-block;background-image:url(' + cat + ');background-repeat:no-repeat; background-position:center;background-size:contain;width:15px;height:15px;background-color:transparent;border-radius:10px;margin:auto 0 -2.5px"></span> <b>'+title+' (' + date.substring(0, 4) + ')</b></span></a>'}ct.innerHTML=content}; var news_post=document.createElement('script');news_post.src='/feeds/posts/summary?redirect=false&alt=json-in-script&orderby=updated&max-results=15&callback=newsPosts';document.getElementsByTagName('head')[0].appendChild(news_post);
function randomPosts(a){var e=shuffleArray(a.feed.entry),title,link,cat,date,img,content="",ct=document.getElementById("random-posts");for(var i=0;i<12;i++){for(var j=0;j<e[i].category.length;j++){
if(e[i].category[j].term=='Mobile Legends: Bang Bang'){var cat='https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEhsFeYJetvdMrSXfy2kZRlbtUl9OXWTH5jKoTjTOAdVp6U7MhIk2pAVo5JQCL4VogIUFyt8z_uPHLVWdEfUyw0ghgz29wrgnla39YnRZAMSHx4rxw05PK2Dgbm5-Bu5S6SJ_t541Xj3qEVZ6upSGxqSiJCLt08L-R0sc0VZCFBtsTQvxo1WI73ZJbLFzQ/w100-rw/MLBB.png'}
if(e[i].category[j].term=='League of Legends: Wild Rift'){var cat='https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEjkY_rmNBv9SPNflhBzM6FZLK4BIDXBk5nUytlfvLCaCLspM9d6JVVrsFdHLY8Jw3wRrWNmYMIQgNgCkjSHEFINK64tvx-piJUp73FoioNVTG84GZayw-ybT2RDGnsKSXcVzQAFv9nMhxpoyP2jRbrLlRl-uz7L97rfcub47xmimM2xO34dZDzLSX_ApA/w100-rw/LOLWR.png'}
if(e[i].category[j].term=='League of Legends'){var cat='https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEhELQD0dWEUqEoyDDlmoaUtDulEkEA_Md0Ag583lCStNJnlEY2Sw7GJyNHXL_DBGcpdxc31PkdJYEwRRfTEraCxjpSeTt-bEXK8H841v7fRZbnpGqwbLZAuhWNAbC7sYNAUA5nMnCvoJO08jS7vQu3b8MfuVRMZV2gsbS2tI72ejESkuF3jGgFwPAZWiQ/w100-rw/League_of_Legends.png'}
if(e[i].category[j].term=='Arena of Valor'){var cat='https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEgCDOsHeQvFe_vr9RFsy1zkYVxdPcrlmJ6vd6VGQT4aK5Z9d5tZGkvIaTHZEXjxwihLrxVHbXMcsebvGR79mITEoAWHX-EtbxnWCMRykW94Mt1vbi0hnumSiv_wBdiD5bEF6AJ-se9lsCVYHfvKYBKQQ6XhOpC7M31p4FFMs1q9rFerPI5POVrVXkajEQ/w100-rw/AOV.png'}
if(e[i].category[j].term=='Onmyoji Arena'){var cat='https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEh0cv-szl8E8HiaekfRq1vs7hV67mcKuaUX8huK2lBOkbb4LVCqhBVTBjFoL4rbEeJSqpAfidHuO2CeTTpF3Fr_XQr1cCNkBVcfXzGO5D-6jIVp6xVPeGTdBelGW67WDTGcJshnZLUBHTLyuoe3eCDKslIfuc62iNwp6QlDKjGGJ8pB4cminJPB1YrFxw/w100-rw/ONMYOJI.png'}} var title=e[i].title.$t; for (var l=0;l<e[i].link.length;l++){if (e[i].link[l].rel=="alternate"){var link= e[i].link[l].href;break}}; var date=e[i].published.$t;try {img = e[i].media$thumbnail.url} catch (h) {s = e[i].content.$t;a = s.indexOf('<img');b = s.indexOf('src="', a);c = s.indexOf('"', b + 5);d = s.substr(b + 5, c - b - 5);if (a != -1 && b != -1 && c != -1 && d != "") {img = d}}
content+='<div class="list"><a href="' + link + '" rel="nofollow"><div class="item-thumbnail" style="background-image: url(' + img + ')"><div class="post-date" style="position:absolute;top:0;right:0;padding:2px;font-size:50%;background:#ff0000;color:#ffffff;border-radius:15px">' + date.substring(0, 4) + '</div><div class="caty" style="display:block;position:absolute;bottom:5px;left:5px;background-image: url(' + cat + ');background-repeat: no-repeat; background-position: center;background-size:contain;width:14px;height:14px;background-color:rgba(0,0,0,.7);border-radius:2px"></div></div><div class="notranslate item-title">' + title + '</div></div>'}ct.innerHTML=content};
function shuffleArray(arr){var i=arr.length,j,temp;if(i===0)return false;while(--i){j=Math.floor(Math.random()*(i+1));temp=arr[i];arr[i]=arr[j];arr[j]=temp}return arr}var random_post=document.createElement('script');random_post.src='/feeds/posts/default?alt=json-in-script&orderby=published&max-results=999&callback=randomPosts';document.getElementsByTagName('head')[0].appendChild(random_post);
var lazyadsense = false;
window.addEventListener("scroll", function(){
if ((document.documentElement.scrollTop != 0 && lazyadsense === false) || (document.body.scrollTop != 0 && lazyadsense === false)) {
(function() { var adG = document.createElement('script'); adG.setAttribute('crossorigin','anonymous'); adG.async = true; adG.src = 'https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-2746726314208711'; var scG = document.getElementsByTagName('script')[0]; scG.parentNode.insertBefore(adG, scG); })();
lazyadsense = true;}}, true); (adsbygoogle = window.adsbygoogle || []).push({google_ad_client: "ca-pub-2746726314208711",enable_page_level_ads: true}); var logourl=$(".logo-container a").attr('href');
$(".mysiteurl").html(logourl); var logoalt=$(".logo-container img.logo").attr('alt');
$(".mysitename").html(logoalt); function getCurrentYear(){var e=new Date;return e.getFullYear()}el=document.getElementById("current-year"),el.innerHTML=getCurrentYear();
var LazyAnalytics=false;window.addEventListener("scroll",function(){(0!=document.documentElement.scrollTop&&false===LazyAnalytics||0!=document.body.scrollTop&&false===LazyAnalytics)&&(!function(){var e=document.createElement("script");e.type="text/javascript",e.async=true,e.src="https://www.googletagmanager.com/gtag/js?id=G-W2W7H703Y1";var a=document.getElementsByTagName("script")[0];a.parentNode.insertBefore(e,a)}(),LazyAnalytics=true)},true);
window.dataLayer = window.dataLayer || []; function gtag(){dataLayer.push(arguments);} gtag('js', new Date()); gtag('config', 'G-W2W7H703Y1');